name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Selenoid
      - name: Download CM tool
        run: curl -s https://aerokube.com/cm/bash | bash

      - name: Start Selenoid
        run: ./cm selenoid start --browsers 'chrome' --last-versions 1 --force
      #

      - name: Run tests
        run: |
          ./gradlew \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -Dselenide.browser=chrome \
            -Dselenide.browserSize=1920x1080 \
            -Dselenide.headless=true \
            clean test