name: Test
on:
  push:
  workflow_dispatch:
    inputs:
      runClean:
        description: "Run with 'clean'?"
        type: boolean
        default: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew ${{ inputs.runClean == 'true' && 'clean test' || 'test' }}
